#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "abort-install" ] || [ "$1" = "disappear" ] ; then
	dpkg-divert --package opentmpfiles --remove --rename \
        --divert /bin/systemd-tmpfiles.real /bin/systemd-tmpfiles
fi

if [ "abort-upgrade" = "$1" ] && dpkg --compare-versions "$2" lt 0.2+2019.05.21.git.44a55796ba-3; then
    dpkg-divert --package opentmpfiles --remove --rename \
        --divert /bin/systemd-tmpfiles.real /bin/systemd-tmpfiles
fi

#DEBHELPER#

exit 0
